import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(
  await readFile(path.join(root, 'src/tokens.json'), 'utf8'),
);
const categories = JSON.parse(
  await readFile(path.join(root, 'src/categories.json'), 'utf8'),
);
const out = path.join(root, 'generated');
await mkdir(out, { recursive: true });
const css = ['/* Generated by scripts/generate.mjs; do not edit. */'];
for (const [theme, values] of Object.entries(tokens.color)) {
  css.push(
    theme === 'light'
      ? ':root, [data-theme="light"] {'
      : '[data-theme="dark"] {',
  );
  for (const [name, value] of Object.entries(values))
    css.push(`  --${name.replaceAll('.', '-')}: ${value};`);
  css.push('}');
}
for (const [name, value] of Object.entries(tokens.typography.fontFamily))
  css.push(`:root { --font-${name}: "${value}"; }`);
for (const [name, value] of Object.entries(tokens.typography.fontSize))
  css.push(`:root { --font-size-${name}: ${value}px; }`);
css.push(
  `:root { --font-variant-numeric: ${tokens.typography.fontVariantNumeric}; font-variant-numeric: var(--font-variant-numeric); }`,
);
const auroraStops = tokens.gradient.aurora.stops
  .map((stop) => `var(--${stop.replaceAll('.', '-')})`)
  .join(', ');
css.push(
  `:root { --gradient-aurora: linear-gradient(${tokens.gradient.aurora.angleDegrees}deg, ${auroraStops}); }`,
);
for (const [name, value] of Object.entries(tokens.radius))
  css.push(`:root { --radius-${name}: ${value}px; }`);
for (const [name, value] of Object.entries(tokens.motion.spring))
  css.push(`:root { --motion-spring-${name}: ${value}; }`);
css.push(
  `:root { --motion-aurora-loop-seconds: ${tokens.motion.auroraLoopSeconds}s; --motion-orbit-revolution-seconds: ${tokens.motion.orbitRevolutionSeconds}s; }`,
);
for (const mode of ['light', 'dark']) {
  const selector =
    mode === 'light' ? ':root, [data-theme="light"]' : '[data-theme="dark"]';
  css.push(`${selector} {`);
  categories.forEach((code, index) => {
    css.push(
      `  --category-${code.toLowerCase().replaceAll('_', '-')}: ${categoryColor(index, categories.length, mode)};`,
    );
  });
  css.push('}');
}
for (const mode of ['light', 'dark']) {
  const selector =
    mode === 'light' ? ':root, [data-theme="light"]' : '[data-theme="dark"]';
  css.push(`${selector} {`);
  for (const [name, value] of Object.entries(tokens.memberAccent.slots))
    css.push(`  --${name.replaceAll('.', '-')}: ${value[mode]};`);
  css.push('}');
}
for (const [state, values] of Object.entries(
  tokens.memberAccent.scopeSwitcherStates,
))
  css.push(
    `:root { --scope-switcher-${state}-indicator-stroke-width: ${values.selectionIndicatorStrokeWidthPx}px; }`,
  );
const theme = {
  ...tokens,
  categoryHue: Object.fromEntries(
    categories.map((code, index) => [
      code,
      {
        light: categoryColor(index, categories.length, 'light'),
        dark: categoryColor(index, categories.length, 'dark'),
      },
    ]),
  ),
};
const cssText = execFileSync(
  path.join(root, '../../node_modules/.bin/prettier'),
  ['--stdin-filepath', path.join(out, 'tokens.css')],
  { input: `${css.join('\n')}\n`, encoding: 'utf8' },
);
await writeFile(path.join(out, 'tokens.css'), cssText);
const nativeJson = execFileSync(
  path.join(root, '../../node_modules/.bin/prettier'),
  ['--stdin-filepath', path.join(out, 'theme.native.json')],
  { input: `${JSON.stringify(theme, null, 2)}\n`, encoding: 'utf8' },
);
await writeFile(path.join(out, 'theme.native.json'), nativeJson);

function categoryColor(index, count, mode) {
  const hue = Number(((index * 360) / count).toFixed(4));
  const lightness = mode === 'light' ? 0.58 : 0.72;
  return `oklch(${lightness} 0.14 ${hue})`;
}
