import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const tokens = JSON.parse(
  await readFile(path.join(root, 'src/tokens.json'), 'utf8'),
);
const categories = JSON.parse(
  await readFile(path.join(root, 'src/categories.json'), 'utf8'),
);
const out = path.join(root, 'generated');
await mkdir(out, { recursive: true });
const css = ['/* Generated by scripts/generate.mjs; do not edit. */'];
for (const [theme, values] of Object.entries(tokens.color)) {
  css.push(
    theme === 'light'
      ? ':root, [data-theme="light"] {'
      : '[data-theme="dark"] {',
  );
  for (const [name, value] of Object.entries(values))
    css.push(`  --${name.replaceAll('.', '-')}: ${value};`);
  css.push('}');
}
for (const [name, value] of Object.entries(tokens.typography.fontFamily))
  css.push(`:root { --font-${name}: "${value}"; }`);
for (const [name, value] of Object.entries(tokens.typography.fontSize))
  css.push(`:root { --font-size-${name}: ${value}px; }`);
for (const [name, value] of Object.entries(tokens.radius))
  css.push(`:root { --radius-${name}: ${value}px; }`);
for (const [name, value] of Object.entries(tokens.motion.spring))
  css.push(`:root { --motion-spring-${name}: ${value}; }`);
css.push(
  `:root { --motion-aurora-loop-seconds: ${tokens.motion.auroraLoopSeconds}s; --motion-orbit-revolution-seconds: ${tokens.motion.orbitRevolutionSeconds}s; }`,
);
const theme = {
  ...tokens,
  categoryHue: Object.fromEntries(
    categories.map((code, index) => [
      code,
      {
        light: categoryColor(index, categories.length, 'light'),
        dark: categoryColor(index, categories.length, 'dark'),
      },
    ]),
  ),
};
const cssText = execFileSync(
  path.join(root, '../../node_modules/.bin/prettier'),
  ['--stdin-filepath', 'tokens.css'],
  { input: `${css.join('\n')}\n`, encoding: 'utf8' },
);
await writeFile(path.join(out, 'tokens.css'), cssText);
await writeFile(
  path.join(out, 'theme.native.json'),
  `${JSON.stringify(theme, null, 2)}\n`,
);

function categoryColor(index, count, mode) {
  const hue = Number(((index * 360) / count).toFixed(4));
  const lightness = mode === 'light' ? 0.58 : 0.72;
  return `oklch(${lightness} 0.14 ${hue})`;
}
