import { MockBankProvider, detectRecurring, monthlyTotal } from './src/core.mjs';
const provider = new MockBankProvider();
const state = { connected: false, subscriptions: [], view: 'dashboard' };
const content = document.querySelector('#content'), connect = document.querySelector('#connect'), modal = document.querySelector('#modal');
const money = n => new Intl.NumberFormat('sv-SE',{style:'currency',currency:'SEK',maximumFractionDigits:0}).format(n);
const date = d => new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'short'}).format(new Date(d+'T12:00:00'));
const active = () => state.subscriptions.filter(s=>s.status!=='dismissed');
function sync(){ document.querySelector('#navCount').textContent=active().length; document.querySelector('#reviewCount').textContent=state.subscriptions.filter(s=>!s.status).length; document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===state.view)); }
function empty(){return `<div class="empty card"><div class="icon">↗</div><h2>See every subscription clearly</h2><p class="muted">Connect the safe sandbox to import sample transactions and find recurring payments.</p><button class="primary" data-connect>Connect sandbox bank</button></div>`}
function dashboard(){if(!state.connected)return empty();const subs=active();return `<div class="hero"><div class="card"><small>ESTIMATED MONTHLY COST</small><div class="metric">${money(monthlyTotal(subs))}</div><span class="trend">Across ${subs.length} active subscriptions</span></div><div class="card"><small>NEXT 30 DAYS</small><div class="metric">${money(monthlyTotal(subs))}</div><span class="muted">${subs.length} expected payments</span></div></div><div class="section-head"><h2>Upcoming payments</h2><button class="ghost" data-view="subscriptions">View all</button></div><div class="grid">${subs.map(card).join('')}</div>`}
function card(s){return `<article class="card sub-card" data-detail="${s.id}"><div class="row"><div class="icon">${s.name[0]}</div><span class="pill ${s.confidence.toLowerCase()}">${s.confidence} confidence</span></div><h3>${s.name}</h3><p class="muted">${s.category} · ${s.cadence}</p><div class="row"><span class="price">${money(s.amount)}</span><span class="muted">${date(s.nextDate)}</span></div></article>`}
function subscriptions(){if(!state.connected)return empty();return `<div class="section-head"><h2>Your subscriptions</h2><span class="muted">${active().length} active · ${money(monthlyTotal(active()))}/month</span></div><div class="list">${active().map(s=>`<div class="list-item" data-detail="${s.id}"><div class="icon">${s.name[0]}</div><div><b>${s.name}</b><div class="muted">${s.category} · ${s.cadence}</div></div><b>${money(s.amount)}</b><span class="muted">Next ${date(s.nextDate)}</span></div>`).join('')}</div>`}
function review(){if(!state.connected)return empty();const pending=state.subscriptions.filter(s=>!s.status);return `<div class="section-head"><div><h2>Review detected payments</h2><p class="muted">Confirm or dismiss. You stay in control.</p></div></div>${pending.length?`<div class="list">${pending.map(s=>`<div class="list-item"><div class="icon">${s.name[0]}</div><div><b>${s.name}</b><div class="muted">${s.paymentCount} monthly payments found</div></div><b>${money(s.amount)}</b><div class="review-actions"><button class="ghost danger" data-dismiss="${s.id}">Not recurring</button><button class="primary" data-confirm="${s.id}">Confirm</button></div></div>`).join('')}</div>`:`<div class="empty card"><div class="icon">✓</div><h2>All caught up</h2><p class="muted">Every detected recurring payment has been reviewed.</p></div>`}`}
function render(){sync();content.innerHTML=state.view==='dashboard'?dashboard():state.view==='subscriptions'?subscriptions():review();}
async function doConnect(){connect.disabled=true;connect.textContent='Importing…';await provider.connect();state.subscriptions=detectRecurring(await provider.getTransactions());state.connected=true;connect.textContent='Sandbox connected ✓';showToast('11 transactions imported · 3 recurring payments detected');render();}
function showToast(message){const el=document.querySelector('#toast');el.textContent=message;el.style.display='block';setTimeout(()=>el.style.display='none',3500)}
function detail(id){const s=state.subscriptions.find(x=>x.id===id);modal.querySelector('#modalBody').innerHTML=`<div class="icon">${s.name[0]}</div><h2>${s.name}</h2><p class="muted">${s.category} · ${s.cadence}</p><div class="metric">${money(s.amount)}</div><p>Expected next payment <b>${date(s.nextDate)}</b></p><p><span class="pill ${s.confidence.toLowerCase()}">${s.confidence} confidence</span> based on timing and amount consistency.</p><div class="history"><h3>Payment history</h3>${s.history.toReversed().map(p=>`<div class="row"><span>${date(p.date)}</span><b>${money(p.amount)}</b></div>`).join('')}</div><p><button class="ghost danger" data-dismiss="${s.id}">Mark as not recurring</button></p>`;modal.showModal()}
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-detail]');if(!b)return;if(b.matches('#connect,[data-connect]'))doConnect();if(b.dataset.view){state.view=b.dataset.view;render()}if(b.dataset.detail)detail(b.dataset.detail);if(b.dataset.confirm){state.subscriptions.find(s=>s.id===b.dataset.confirm).status='confirmed';showToast('Subscription confirmed');render()}if(b.dataset.dismiss){state.subscriptions.find(s=>s.id===b.dataset.dismiss).status='dismissed';modal.close();showToast('Removed from subscriptions');render()}if(b.matches('.close'))modal.close()});
render();
